"""Add security events

Revision ID: 5a1dcff926ae
Revises: 3a1eee9b3150
Create Date: 2026-08-02 23:55:55.714140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a1dcff926ae'
down_revision = '3a1eee9b3150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='new', nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_security_events_severity_valid')),
    sa.CheckConstraint("status IN ('new', 'investigating', 'resolved', 'false_positive')", name=op.f('ck_security_events_status_valid')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_security_events_assigned_to_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_security_events_org_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index('ix_security_events_org_occurred_at', ['org_id', sa.literal_column('occurred_at DESC'), sa.literal_column('id DESC')], unique=False)
        batch_op.create_index('uq_security_events_org_source_external', ['org_id', 'source', 'external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index('uq_security_events_org_source_external')
        batch_op.drop_index('ix_security_events_org_occurred_at')
        batch_op.drop_index(batch_op.f('ix_security_events_assigned_to_id'))

    op.drop_table('security_events')
    # ### end Alembic commands ###
